[workspace]
members = [
        'async',
        'async_web_server',
        'image_to_ascii',
        'smart_pointer',
        'channel',
        'mutex',
        'pattern',
        'unsafe-rust',
        'trait-extends',
        'type-extends',
]
